CREATE TABLE IF NOT EXISTS vdi (
serial INTEGER NOT NULL PRIMARY KEY, 
issuing INTEGER NOT NULL, 
name TEXT NOT NULL, 
address TEXT NOT NULL, 
phone TEXT NOT NULL, 
cause TEXT NOT NULL, 
Prescription TEXT NOT NULL, 
amount TEXT NOT NULL, 
type TEXT NOT NULL, 
count TEXT NOT NULL, 
age TEXT NOT NULL, 
aspect TEXT NOT NULL, 
regimen TEXT NOT NULL, 
dosage TEXT NOT NULL, 
taking TEXT NOT NULL, 
holidays TEXT NOT NULL, 
other TEXT NOT NULL
);
